version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: 3306
      MYSQL_DB: "url_shortener_dev"
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db:/var/lib/mysql
volumes:
  db: